<?php /** @var G3d_View_Codehinting */ $this; ?>

<link href="http://alexgorbatchev.com/pub/sh/current/styles/shThemeDefault.css" rel="stylesheet" type="text/css" />
<script src="http://alexgorbatchev.com/pub/sh/current/scripts/shCore.js"></script>
<script src="http://alexgorbatchev.com/pub/sh/current/scripts/shBrushPhp.js"></script>
<script src="http://alexgorbatchev.com/pub/sh/current/scripts/shBrushXml.js"></script>

<style>
	code {
		background-color: #FFFFFF;
	}
</style>
<script>
	 SyntaxHighlighter.all()
</script>

<div class="row">
	<div class="col-md-12 col-xs-12">
		<h2>Bootstrap progress bar</h2>

		<p>This view helper generates the HTML for the Bootstrap progress 
			bar component, it allows you to provide feedback on the progress 
			of a workflow or action.</p>
			
		<?php echo $this->bootstrapProgressBar(60); ?>
		<?php echo $this->bootstrapProgressBar(25); ?>
		<?php echo $this->bootstrapProgressBar(33)->showLabel(); ?>
		<?php echo $this->bootstrapProgressBar(-101)->showLabel(); ?>
		<?php echo $this->bootstrapProgressBar(70)->modifierClass('warning'); ?>
		<?php echo $this->bootstrapProgressBar(60)->modifierClass('awarning'); ?>
		<?php echo $this->bootstrapProgressBar(70)->modifierClass('warning')->showLabel(); ?>
	</div>
</div>