<div class="row">
	<div class="col-md-8 col-md-offset-2 col-xs-12">
		<h2>View Helpers</h2>
		
		<ul>
			<li><a href="/helper/view/bootstrap-nav">Bootstrap nav</a> - 
				Generates the HTML for a Bootstrap nav component.
			</li>
			<li><a href="/helper/view/bootstrap-label">Bootstrap label</a> - 
				Generates the HTML for a Bootstrap label.
			</li>
			<li><a href="/helper/view/bootstrap-glyphicon">Bootstrap 
				glyphicon</a> - Generates the HTML for a Bootstrap glyphicon.
			</li>
			<li><a href="/index/index/simple-pagination">Simple 
				pagination</a> - Generates next, previous, m of n html based 
				on the params passed into the view helper.
			</li>
		</ul>
		
		<h2>Utility Classes</h2>
		
		<ul>
			<li><a href="/index/resizer/index">Image resizer</a> - 
			Reisze the supplied image allowing the user to define 
			the background canvas color, desired size, quality/compression, image 
			suffix and whether or not resized image maintains the aspect ratio 
			of the original.</li>
			<li><a href="/index/crop/index">Image cropper</a> - 
			Crop the supplied image allowing the user to define the crop selection 
			and the quality/compression for the cropped image.</li>
		</ul>
	</div>
</div>