<div class="row">
	<div class="col-md-8 col-md-offset-2 col-xs-12">
		<h2>View Helpers</h2>
		
		<ul>
			<li><a href="/helper/view/bootstrap-nav">Bootstrap nav</a> - 
				Generates the HTML for a Bootstrap nav component.
			</li>
			<li><a href="/helper/view/bootstrap-label">Bootstrap label</a> - 
				Generates the HTML for a Bootstrap label.
			</li>
			<li><a href="/helper/view/bootstrap-glyphicon">Bootstrap 
				glyphicon</a> - Generates the HTML for a Bootstrap glyphicon.
			</li>
			<li><a href="/helper/view/simple-pager">Simple pager</a> - 
				Generates the HTML for a simple pager featuring either an 
				item or page based description, all text configurable
			</li>
			<li><a href="/helper/view/bootstrap-table">Bootstrap 
				table</a> - Very simple view helper to assist with generating 
				the HTML for a table.
			</li>
			<li><a href="/helper/view/bootstrap-badge">Bootstrap 
				badge</a> - Generates the HTML for the Bootstrap badge 
				component.
			</li>
		</ul>
		
		<h2>Utility Classes</h2>
		
		<ul>
			<li><a href="/utility/image/resizer">Image resizer</a> - 
				Resize the supplied image allowing the user to define 
				the background canvas color, desired size, quality/compression, 
				image suffix and whether or not resized image maintains the 
				aspect ratio of the source.</li>
			<li><a href="/utility/image/crop">Image cropper</a> - 
			Crop the supplied image allowing the user to define the crop selection 
			and the quality/compression for the cropped image.</li>
		</ul>
	</div>
</div>