<?php
class Bootstrap extends Zend_Application_Bootstrap_Bootstrap
{
    /**
    * Set PHP defaults, in this case the timesize, not safe to rely on the 
    * server setting
    * 
    * @return void
    */
    public function _initPhpDefaults() 
    {
        // Not safe to relay on servers timezone 
        if (function_exists('date_default_timezone_set')) {
            date_default_timezone_set('Europe/London');
        }
    }
    
    /**
    * Set doc type, set to XHTML strict, ensures that any code generated by 
    * the Zend view helper is correct
    */
    public function _initDocType() 
    {
        $this->bootstrap('layout');
        $this->getResource('layout')->getView()->doctype('XHTML1_STRICT');
    }
    
    /**
    * Set up namespaces for our library code, going to be serveral libraries, 
    * base library code will reside in Dlayer, specific module library code goes 
    * in a folder with the same name as the module
    * 
    * @return void
    */
    function _initNamespaces() 
    {
        
    }
    
    /**
    * Setup view helpers, view helpers exists only inside the Dlayer library, 
    * shared between all modules, this appears to be a Zend issue at the moment 
    * so just need to work around it
    * 
    * @return void
    */
    function _initViewHelpers() 
    {
        
    }
    
    /**
    * Setup action helpers, exist only within the Dlayer library, shared between 
    * all the modules, as per view helpers this appears to be a Zend issue so 
    * just going to work with it
    * 
    * @return void
    */
    public function _initActionHelpers() 
    {
        
    }
        
    /**
    * Connect to the default database and set the default adapter
    * 
    * @return void
    */
    public function _initDatabaseConnection() 
    {
        
    }
}