<?php
class Bootstrap extends Zend_Application_Bootstrap_Bootstrap
{
    /**
    * Set PHP defaults, in this case the timesize, not safe to rely on the 
    * server setting
    * 
    * @return void
    */
    public function _initPhpDefaults() 
    {
        // Not safe to relay on servers timezone 
        if (function_exists('date_default_timezone_set')) {
            date_default_timezone_set('Europe/London');
        }
    }
    
    /**
    * Set doc type, set to XHTML strict, ensures that any code generated by 
    * the Zend view helper is correct
    */
    public function _initDocType() 
    {
        $this->bootstrap('layout');
        $this->getResource('layout')->getView()->doctype('XHTML1_STRICT');
    }
    
    /**
    * Set up namespaces for our library code
    * 
    * @return void
    */
    function _initNamespaces() 
    {
        Zend_Loader_Autoloader::getInstance()->registerNamespace('G3d_');
    }
    
    /**
    * Setup view helpers, view helpers need to be added to the library, 
    * they will then be accessible to all modules.
    *
    * @return void
    */
    function _initViewHelpers()
    {
        $renderer = Zend_Controller_Action_HelperBroker::getStaticHelper(
        'viewRenderer');
        $renderer->initView();
        $renderer->view->addHelperPath('G3d/View/',
                                       'G3d_View');
    }

    /**
    * Setup action helpers, action helpers need to be added to the library, 
    * they will then be accessible to all modules.
    *
    * @return void
    */
    public function _initActionHelpers()
    {
        Zend_Controller_Action_HelperBroker::addPath('G3d/Action/',
                                                     'G3d_Action');
    }
        
    /**
    * Connect to the default database and set the default adapter
    * 
    * @return void
    */
    public function _initDatabaseConnection() 
    {
        
    }
}