<?php echo $this->doctype(Zend_View_Helper_Doctype::XHTML1_STRICT) . "\r\n"; ?>
<html xmlns="http://www.w3.org/1999/xhtml">
    <head>
        <title>Zend helpers examples</title>
        <meta http-equiv="Content-Type" content="text/html; charset=utf-8" />
        <link href="<?php echo $this->baseUrl('styles/app.css'); ?>" rel="stylesheet" media="" type="text/css" />
    </head>
    <body>
        <div id="content">
            <?php echo $this->layout()->content; ?>
            
            <div id="footer">
            <p>Copyright &copy; G3D Development Limited 
            2010-<?php echo date('Y'); ?></p>
            </div>
        </div>
    </body>
</html>