<?php echo $this->doctype(Zend_View_Helper_Doctype::XHTML1_STRICT) . "\r\n"; ?>
<html xmlns="http://www.w3.org/1999/xhtml">
    <head>
        <title>Zend helpers examples</title>
        <meta http-equiv="Content-Type" content="text/html; charset=utf-8" />
        <link href="<?php echo $this->baseUrl('styles/app.css'); ?>" rel="stylesheet" media="" type="text/css" />
    </head>
    <body>
        <div id="content">
            <h1>Zend helpers examples</h1>
            
            <p>This sample site provides examples for all the action and view 
            helpers in the <a href="https://github.com/g3d-development/zend-helpers">https://github.com/g3d-development/zend-helpers</a> 
            project on GitHub.</p>
            
            <p>The sample site will also include examples for the utility 
            classes where appropriate.</p>
            
            <p>This site requires Zend Framework, at the time of writing 
            version 1.12.</p>

            <?php echo $this->layout()->content; ?>
            
            <p><a href="/">Return to index</a></p>
            
            <div id="footer">
            <p>Copyright &copy; G3D Development Limited 
            2010-<?php echo date('Y'); ?></p>
            </div>
        </div>
    </body>
</html>