<h2>View helpers</h2>

<ul>
    <li><a href="/module/index/simple-pagination">Simple pagination</a> - 
    Generates next, previous, m of n html based on the params passed 
    into the view helper.</li>
</ul>

<h2>Utility classes</h2>

<ul>
    <li><a href="/module/resizer/index">Image resizer</a> - 
    Reize the supplied image allowing the user to define 
    the background canvas color, desired size, quality/compression, image 
    suffix and whether or not resized image maintains the aspect ratio 
    of the original.</li>
</ul>